### ISSUE TITLE
Update for new Lightsail regions

### ISSUE THREAD

**Issue by paulobrien** [awslabs/lightsail-auto-snapshots#4]
This now requires updating for additional lightsail regions.

**Comment by jpignata** [comment]
Thanks, @paulobrien! Any feedback on #5?

**Comment by paulobrien** [comment]
I think it'd be useful to be able to specify the region. For example, I have lightsail resources in multiple regions and I'd like to back them all up... so I would need to run the script once for each region I assume, passing the region as a parameter perhaps?

**Comment by paulobrien** [comment]
Thinking about it, not sure if CloudFormation will b0rk at being run several times with the same name? Might need to identify the region in it.

**Comment by jpignata** [comment]
A user can do this in my current pull by specifying `AWS_DEFAULT_REGION` as an environment variable before `bin/deploy`. I do see some utility in region being an explicit parameter, but I shy away from multiple positional parameters because it's too easy to make an error. How about we move both parameters to environment variables that can be specified before the command, i.e.:

```console
## Install in US East (Ohio) and retain snapshots for 30 days
REGION=us-east-2 DAYS=30 bin/deploy

## Install in the CLI's configured default region and retain snapshots for 90 days
DAYS=90 bin/deploy

## Install in EU (Ireland) and retain snapshots for 14 days
REGION=eu-west-1 bin/deploy
```

`DAYS` would default to 14 if not provided and `REGION` would default to the CLI's configured default region.

To your second point: the stack will be created in an individual region which is a separate CloudFormation namespace so there isn't any chance of a collision. You can have the same stack in multiple regions with the same name, but you cannot run this script twice in the same region.

Thoughts?

**Comment by paulobrien** [comment]
Looks great, nice work. :)

**Comment by jpignata** [comment]
Cool! I've updated the pull. Let me know if you have any feedback.
